apiVersion: v1
kind: Service
metadata:
  name: spark-master
spec:
  selector:
    app: spark-cluster
  ports:
    - port: 7077
      targetPort: 7077
      name: spark
    - port: 8080
      targetPort: 8080
      name: http
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: spark-ui-proxy
spec:
  selector:
    app: spark-cluster
  ports:
    - port: 80
      targetPort: 80
  type: NodePort
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: spark-cluster
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: spark-cluster
    spec:
      containers:
        - name: spark-master
          image: gettyimages/spark:2.0.2-hadoop-2.7
          ports:
            - containerPort: 7077
            - containerPort: 8080
          args: ["bin/spark-class", "org.apache.spark.deploy.master.Master","-h","spark-master"]
          resources:
            requests:
              cpu: 100m
      - name: spark-worker
        image: gettyimages/spark:2.0.2-hadoop-2.7
        ports:
          - containerPort: 8081
          - containerPort: 8881
        args: ["bin/spark-class", "org.apache.spark.deploy.worker.Worker","spark://spark-master:7077"]
        resources:
          requests:
            cpu: 100m
      - name: spark-ui-proxy
          image: elsonrodriguez/spark-ui-proxy:1.0
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 100m
          args:
            - spark-master:8080
          livenessProbe:
              httpGet:
                path: /
                port: 80
              initialDelaySeconds: 120
              timeoutSeconds: 5
