apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: spark-worker
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: spark-worker
    spec:
      containers:
        - name: spark-worker
          image: gettyimages/spark:2.0.2-hadoop-2.7
          resources:
            limits:
              cpu: 1000m
              memory: 4000Mi
            requests:
              cpu: 200m
              memory: 150Mi
          ports:
            - containerPort: 8081
          args: ["bin/spark-class", "org.apache.spark.deploy.worker.Worker","spark://sparkmaster:7077"]
