apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: oneflare/insights-zeppelin-nginx:20170303-4
          imagePullPolicy: Always
          resources:
            limits:
              cpu: 50m
              memory: 50Mi
            requests:
              cpu: 20m
              memory: 20Mi
          ports:
            - containerPort: 80
            - containerPort: 443
            - containerPort: 7077
          # livenessProbe:
          #     httpGet:
          #       path: /
          #       port: 80
          #     initialDelaySeconds: 30
          #     timeoutSeconds: 5
      imagePullSecrets:
      - name: oneflaredockerhub
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  ports:
    - port: 80
      targetPort: 80
      name: http
    - port: 443
      targetPort: 443
      name: https
    - port: 7077
      targetPort: 7077
      name: spark-port
  selector:
    app: nginx
  type: LoadBalancer
