apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: spark-master
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: spark-master
    spec:
      containers:
        - name: spark-master
          image: oneflare/insights-zeppelin-spark:20170303-1
          resources:
            limits:
              cpu: 500m
              memory: 1000Mi
            requests:
              cpu: 100m
              memory: 100Mi
          ports:
            - containerPort: 4040
            # - containerPort: 6066
            - containerPort: 7077
            - containerPort: 8080
          env:
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: zeppelin-deploy-secrets
                  key: AWS_SECRET_ACCESS_KEY
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: zeppelin-deploy-secrets
                  key: AWS_ACCESS_KEY_ID
            - name: ZEPPELIN_CONF_S3_BUCKET
              valueFrom:
                secretKeyRef:
                  name: zeppelin-deploy-secrets
                  key: ZEPPELIN_CONF_S3_BUCKET
            - name: SPARK_PUBLIC_DNS
              value: spark.monkey.io
            - name: SPARK_MASTER_HOST
              value: 0.0.0.0
            - name: SPARK_MASTER_PORT
              value: '7077'
          args: ["spark-master"]
      imagePullSecrets:
      - name: oneflaredockerhub
---
kind: Service
apiVersion: v1
metadata:
  name: sparkmaster
spec:
  ports:
    # - port: 6066
    #   targetPort: 6066
    #   name: rest
    - port: 7077
      targetPort: 7077
      name: spark
    - port: 8080
      targetPort: 8080
      name: http
  selector:
    app: spark-master
