apiVersion: v1
kind: Service
metadata:
  name: spark-ui-proxy
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: spark-master
  type: LoadBalancer
---
kind: Service
apiVersion: v1
metadata:
  name: sparkmaster
spec:
  ports:
    - port: 7077
      targetPort: 7077
      name: spark
    - port: 8080
      targetPort: 8080
      name: http
  selector:
    app: spark-master
  # type: NodePort
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: zeppelin-service
# spec:
#   ports:
#     - port: 8080
#       targetPort: 8080
#       name: http
#     - port: 8081
#       targetPort: 8081
#       name: socket
#   selector:
#     app: zeppelin
#   type: LoadBalancer
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: spark-master
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: spark-master
    spec:
      containers:
        - name: spark-master
          image: nathanscully/zeppelin-kube
          resources:
            limits:
              cpu: 500m
              memory: 500Mi
            requests:
              cpu: 250m
              memory: 150Mi
          ports:
            - containerPort: 7077
            - containerPort: 8080
          args: ["bin/spark-class", "org.apache.spark.deploy.master.Master"]
        # - name: spark-worker
        #   image: gettyimages/spark:2.0.2-hadoop-2.7
        #   resources:
        #     limits:
        #       cpu: 1000m
        #       memory: 4000Mi
        #     requests:
        #       cpu: 200m
        #       memory: 1000Mi
        #   ports:
        #     - containerPort: 8081
        #   args: ["bin/spark-class", "org.apache.spark.deploy.worker.Worker","spark://sparkmaster:7077"]
        - name: spark-ui-proxy
          image: elsonrodriguez/spark-ui-proxy:1.0
          ports:
            - containerPort: 80
          resources:
            limits:
              cpu: 200m
              memory: 200Mi
            requests:
              cpu: 100m
              memory: 100Mi
          args:
            - sparkmaster:8080
          livenessProbe:
              httpGet:
                path: /
                port: 80
              initialDelaySeconds: 120
              timeoutSeconds: 5
# ---
# apiVersion: extensions/v1beta1
# kind: Deployment
# metadata:
#   name: zeppelin
# spec:
#   replicas: 1
#   template:
#     metadata:
#       labels:
#         app: zeppelin
#     spec:
#       containers:
#         - name: zeppelin
#           image: nathanscully/zeppelin-kube
#           resources:
#             limits:
#               cpu: 500m
#               memory: 1000Mi
#             requests:
#               cpu: 200m
#               memory: 250Mi
#           ports:
#             - containerPort: 8080
#             - containerPort: 8081
#           env:
#             - name: AWS_SECRET_ACCESS_KEY
#               valueFrom:
#                 secretKeyRef:
#                   name: zeppelin-deploy-secrets
#                   key: AWS_SECRET_ACCESS_KEY
#             - name: AWS_ACCESS_KEY_ID
#               valueFrom:
#                 secretKeyRef:
#                   name: zeppelin-deploy-secrets
#                   key: AWS_ACCESS_KEY_ID
#             - name: ZEPPELIN_CONF_S3_BUCKET
#               valueFrom:
#                 secretKeyRef:
#                   name: zeppelin-deploy-secrets
#                   key: ZEPPELIN_CONF_S3_BUCKET
