apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: spark-worker
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: spark-worker
    spec:
      containers:
        - name: spark-worker
          image: oneflare/insights-zeppelin-spark:20170303-1
          resources:
            limits:
              cpu: 1000m
              memory: 4000Mi
            requests:
              cpu: 100m
              memory: 100Mi
          ports:
            - containerPort: 8081
            - containerPort: 8881
            # - containerPort: 4040
          env:
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: zeppelin-deploy-secrets
                  key: AWS_SECRET_ACCESS_KEY
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: zeppelin-deploy-secrets
                  key: AWS_ACCESS_KEY_ID
            - name: ZEPPELIN_CONF_S3_BUCKET
              valueFrom:
                secretKeyRef:
                  name: zeppelin-deploy-secrets
                  key: ZEPPELIN_CONF_S3_BUCKET
            - name: SPARK_WORKER_PORT
              value: '8881'
            - name: SPARK_WORKER_WEBUI_PORT
              value: '8081'
          args: ["spark-worker"]
      imagePullSecrets:
      - name: oneflaredockerhub
