apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: spark-worker
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: spark-worker
    spec:
      containers:
        - name: spark-worker
          image: oneflare/insights-zeppelin-spark:latest
          resources:
            limits:
              cpu: 1000m
              memory: 4000Mi
            requests:
              cpu: 200m
              memory: 1000Mi
          ports:
            - containerPort: 8081
          args: ["spark-worker"]
      imagePullSecrets:
      - name: oneflaredockerhub
