apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: spark-worker
spec:
  replicas: 4
  template:
    metadata:
      labels:
        app: spark-worker
    spec:
      containers:
        - name: spark-worker
          image: oneflare/insights-zeppelin-spark:latest
          resources:
            limits:
              cpu: 1000m
              memory: 4000Mi
            requests:
              cpu: 200m
              memory: 1000Mi
          ports:
            - containerPort: 8081
          args: ["spark-worker"]
          # args: ["bin/spark-class", "org.apache.spark.deploy.worker.Worker","spark://sparkmaster:7077"]
          # command: ["/bin/bash", "/usr/spark-2.0.2/bin/spark-class", "org.apache.spark.deploy.worker.Worker","spark://sparkmaster:7077"]
      imagePullSecrets:
      - name: oneflaredockerhub
