apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: zeppelin
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: zeppelin
    spec:
      containers:
        - name: zeppelin
          image: oneflare/insights-zeppelin-spark:20170301-1
          resources:
            limits:
              cpu: 2000m
              memory: 4000Mi
            requests:
              cpu: 100m
              memory: 100Mi
          ports:
            - containerPort: 8080
            - containerPort: 8081
            - containerPort: 4040
          env:
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: zeppelin-deploy-secrets
                  key: AWS_SECRET_ACCESS_KEY
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: zeppelin-deploy-secrets
                  key: AWS_ACCESS_KEY_ID
            - name: ZEPPELIN_CONF_S3_BUCKET
              valueFrom:
                secretKeyRef:
                  name: zeppelin-deploy-secrets
                  key: ZEPPELIN_CONF_S3_BUCKET
          args: ["zeppelin"]
      #     volumeMounts:
      #     - mountPath: "/usr/zeppelin/conf"
      #       name: zeppelin-pvc
      # volumes:
      #   - name: zeppelin-pvc
      #     persistentVolumeClaim:
      #       claimName: zeppelin-pvc
      imagePullSecrets:
      - name: oneflaredockerhub
---
apiVersion: v1
kind: Service
metadata:
  name: zeppelin-service
spec:
  ports:
    - port: 8080
      targetPort: 8080
      name: http
    - port: 8081
      targetPort: 8081
      name: socket
    - port: 4040
      targetPort: 4040
      name: zeppelin-sparkui
  selector:
    app: zeppelin
