apiVersion: v1
kind: PersistentVolume
metadata:
  name: zeppelin-pv
  annotations:
    volume.beta.kubernetes.io/storage-class: "gp2"
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  awsElasticBlockStore:
    volumeID: <volumeID>
    fsType: ext4
