apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: spark-worker
spec:
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: spark-worker
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 50
